---
# Tasks to add VS Code repository for RedHat variants

- name: Add Microsoft signing key
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add VS Code yum repository
  yum_repository:
    name: vscode
    description: Visual Studio Code repository
    file: vscode
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: true
