---
# Tasks for installing VS Code extensions

- name: Get user home directory
  shell: "getent passwd {{ vscode_user }} | cut -f6 -d:"
  register: user_home_dir
  changed_when: false

- name: Set VS Code user data directory fact
  set_fact:
    vscode_user_data_dir: "{{ user_home_dir.stdout }}/.vscode"

- name: Ensure VS Code data directory exists
  file:
    path: "{{ vscode_user_data_dir }}"
    state: directory
    mode: 0750
  become: true
  become_user: "{{ vscode_user }}"

- name: Install VS Code extensions
  command: "code --user-data-dir {{ vscode_user_data_dir }} --install-extension {{ item }}"
  become: true
  become_user: "{{ vscode_user }}"
  loop: "{{ vscode_extensions | default([]) }}"
  register: install_extension
  changed_when: "'successfully installed' in install_extension.stdout"
