---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: kali-vscode
    image: kalilinux/kali-linux-docker
  - name: ubuntu-vscode
    image: ubuntu:18.04
  - name: fedora-vscode
    image: fedora:latest
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  options:
    v: true
  lint:
    name: flake8
