---
- name: Converge
  hosts: all
  vars:
    debian_packages:
      - libx11-xcb1
      - libasound2
    redhat_packages:
      - libX11-xcb
  tasks:
    - name: Install Debian dependencies
      apt:
        name: '{{ debian_packages }}'
      when: ansible_os_family == "Debian" or ansible_os_family == "Kali GNU/Linux"

    - name: Install RedHat dependencies
      package:
        name: '{{ redhat_packages }}'
      when: ansible_os_family == "RedHat"
